export const AUDIO_GET_DEVICES_REQUEST = 'AUDIO_GET_DEVICES_REQUEST'
export const AUDIO_GET_DEVICES_SUCCESS = 'AUDIO_GET_DEVICES_SUCCESS'
export const AUDIO_GET_DEVICES_FAIL = 'AUDIO_GET_DEVICES_FAIL'
export const AUDIO_CHANGE_DEVICE = 'AUDIO_CHANGE_DEVICE'
export const AUDIO_INPUT_DEVICE_DETECTED = 'AUDIO_INPUT_DEVICE_DETECTED'
export const AUDIO_OUTPUT_DEVICE_DETECTED = 'AUDIO_OUTPUT_DEVICE_DETECTED'

export const DEVICE_TYPES = {
    PHONE_INPUT: 'PHONE_INPUT',
    PHONE_OUTPUT: 'PHONE_OUTPUT',
    PHONE_RINGING: 'PHONE_RINGING',
    AUDIO_SOUNDS: 'AUDIO_SOUNDS'
}